### ISSUE TITLE
Unable to show face of the user who joins

### ISSUE THREAD

**Issue by Eddy118** [DipanshKhandelwal/react-native-webrtc-firebase#1]
I have tried your code there's some Issue with it 
exampe
User A => Starts Call
User B => Joins Call
User A Can  see User B steam but
User B Can't  see User A stream even after adding IceCandidates of User A
can you please fix it

**Comment by DipanshKhandelwal** [comment]
Thank you @Eddy118 . Could not get time recently. Will fix it in a couple of days.
If you already worked on something, feel free to raise a PR.

**Comment by Eddy118** [comment]
> Thank you @Eddy118 . Could not get time recently. Will fix it in a couple of days.
> If you already worked on something, feel free to raise a PR.

I am working on it right now hopefully it'll be completed today will share fix with you soon

**Comment by fukuball** [comment]
Same issue, did you guys fix it? @Eddy118 @DipanshKhandelwal

**Comment by DipanshKhandelwal** [comment]
@fukuball Could not work on it yet, will surely check today.

**Comment by Eddy118** [comment]
@fukuball I tried but couldn't solve this issue.

**Comment by selimovict** [comment]
Hi guys 
do you have any solutions or maybe a way to solve problem ?
@fukuball  @Eddy118 ,

**Comment by fukuball** [comment]
> Hi guys
> do you have any solutions or maybe a way to solve problem ?
> @fukuball @Eddy118 ,

no luck, still can't solve this issue

**Comment by andarg** [comment]
Hi, people! Did you find some solution? I got same issue, no idea how to deal with it yet

**Comment by EliHood** [comment]
> Hi, people! Did you find some solution? I got same issue, no idea how to deal with it yet

Are you able to get firebase working on your end ? Are you able to see the data being persisted in your firebase console ?

**Comment by andarg** [comment]
> > Hi, people! Did you find some solution? I got same issue, no idea how to deal with it yet
> 
> Are you able to get firebase working on your end ? Are you able to see the data being persisted in your firebase console ?

yes i am. I get data from both pear but on Join screen event`localPC.onaddstream` nevent never happens
for example my candidate data which i got from call screen  `{"candidate": "candidate:842163049 1 udp 1686052607 109.194.103.180 37785 typ srflx raddr 192.168.1.2 rport 37785 generation 0 ufrag rz/x network-id 4 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "audio"}
`

**Comment by EliHood** [comment]
> > > Hi, people! Did you find some solution? I got same issue, no idea how to deal with it yet
> > 
> > 
> > Are you able to get firebase working on your end ? Are you able to see the data being persisted in your firebase console ?
> 
> yes i am. I get data from both pear but on Join screen event`localPC.onaddstream` event never happens
> for example my candidate data which i got from call screen `{"candidate": "candidate:842163049 1 udp 1686052607 109.194.103.180 37785 typ srflx raddr 192.168.1.2 rport 37785 generation 0 ufrag rz/x network-id 4 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "audio"} `

Any update on your end ? 

also are you adding this line anywhere

`pc.addIceCandidate(e);`

**Comment by andarg** [comment]
> > > > Hi, people! Did you find some solution? I got same issue, no idea how to deal with it yet
> > > 
> > > 
> > > Are you able to get firebase working on your end ? Are you able to see the data being persisted in your firebase console ?
> > 
> > 
> > yes i am. I get data from both pear but on Join screen event`localPC.onaddstream` event never happens
> > for example my candidate data which i got from call screen `{"candidate": "candidate:842163049 1 udp 1686052607 109.194.103.180 37785 typ srflx raddr 192.168.1.2 rport 37785 generation 0 ufrag rz/x network-id 4 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "audio"} `
> 
> Any update on your end ?
> 
> Maybe there could be an issue with the signaling ?

i tested it on few devices and it works same everywhere. May be problem is sequence of exchanging data between screens but i didn't find solution yet

**Comment by DipanshKhandelwal** [comment]
> > > Hi, people! Did you find some solution? I got same issue, no idea how to deal with it yet
> > 
> > 
> > Are you able to get firebase working on your end ? Are you able to see the data being persisted in your firebase console ?
> 
> yes i am. I get data from both pear but on Join screen event`localPC.onaddstream` event never happens
> for example my candidate data which i got from call screen `{"candidate": "candidate:842163049 1 udp 1686052607 109.194.103.180 37785 typ srflx raddr 192.168.1.2 rport 37785 generation 0 ufrag rz/x network-id 4 network-cost 10", "sdpMLineIndex": 0, "sdpMid": "audio"}`

Yeah, I am stuck with this itself. I am not getting the stream.

**Comment by DipanshKhandelwal** [comment]
Fixed by https://github.com/DipanshKhandelwal/react-native-webrtc-firebase/commit/6934ad3c2da1f72b02d9f8070c282f8777ed9712

**Comment by andarg** [comment]
Great job, man!
