### ISSUE TITLE
Getting err while making build

### ISSUE THREAD

**Issue by bilalyaqoob** [DipanshKhandelwal/react-native-webrtc-firebase#7]
> Task :app:installDebug FAILED
Skipping device 'HUAWEI SCL-U31 - 5.1.1' for 'app:debug': minSdkVersion [24] > deviceApiLevel [22]
108 actionable tasks: 90 executed, 18 up-to-date
Note: C:\Users\Dell\Desktop\react-native-webrtc-firebase\node_modules\@react-native-firebase\app\android\src\reactnative\java\io\invertase\firebase\app\ReactNativeFirebaseAppInitProvider.java uses or overrides 
a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Dell\Desktop\react-native-webrtc-firebase\node_modules\react-native-webrtc\android\src\main\java\com\oney\WebRTCModule\WebRTCModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Dell\Desktop\react-native-webrtc-firebase\android\app\src\debug\java\com\webrtc_firebase\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by DipanshKhandelwal** [comment]
Device API level is 22 and it is only supported by devices API level >= 24
I'll need to check if I can make it work for them, by that time can you try to use an emulator with an API level >= 24.
